BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  full_name TEXT NOT NULL,
  roles TEXT[] NOT NULL DEFAULT ARRAY['bidder']::TEXT[],
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  password_hash TEXT NOT NULL,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  contact_number TEXT,
  failed_login_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
  locked_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_roles_valid CHECK (roles <@ ARRAY['bidder', 'donor', 'charity_staff', 'charity', 'admin']::TEXT[])
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx ON users (LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_uidx ON users (LOWER(username));

ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS pending_registrations (
  email TEXT PRIMARY KEY,
  id TEXT NOT NULL,
  username TEXT NOT NULL,
  full_name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  roles TEXT[] NOT NULL,
  otp_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pending_registrations_roles_valid CHECK (roles <@ ARRAY['bidder', 'donor', 'charity_staff', 'charity', 'admin']::TEXT[])
);

CREATE INDEX IF NOT EXISTS pending_registrations_expires_idx ON pending_registrations (expires_at);

CREATE TABLE IF NOT EXISTS login_otps (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  otp_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS login_otps_expires_idx ON login_otps (expires_at);

CREATE TABLE IF NOT EXISTS sessions (
  sid TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  jti_hash TEXT NOT NULL,
  csrf_token_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  absolute_expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '8 hours',
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Migration: add absolute_expires_at to existing databases
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS absolute_expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '8 hours';

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS password_reset_tokens_expires_idx ON password_reset_tokens (expires_at);

-- SFR03 verified email change (OWASP no-MFA, sequential current-first confirmation).
-- One pending change per user. The user first confirms a code sent to their CURRENT
-- address; only then is a code issued to the NEW address (anti-abuse: the new,
-- possibly attacker-chosen, address is never contacted until current control is proven).
CREATE TABLE IF NOT EXISTS email_change_requests (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  new_email TEXT NOT NULL,
  old_email TEXT NOT NULL,
  old_email_otp_hash TEXT NOT NULL,
  new_email_otp_hash TEXT,
  old_email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Migrations for databases created before the sequential flow was introduced.
ALTER TABLE email_change_requests ALTER COLUMN new_email_otp_hash DROP NOT NULL;
ALTER TABLE email_change_requests ADD COLUMN IF NOT EXISTS old_email_confirmed BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS email_change_requests_expires_idx ON email_change_requests (expires_at);

CREATE TABLE IF NOT EXISTS charities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organisation_name TEXT NOT NULL,
  description TEXT NOT NULL,
  document_name TEXT NOT NULL,
  document_mime TEXT NOT NULL CHECK (document_mime IN ('application/pdf', 'image/png', 'image/jpeg')),
  document_sha256 TEXT NOT NULL,
  document_data BYTEA,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS charities_status_idx ON charities (status);
CREATE INDEX IF NOT EXISTS charities_owner_user_id_idx ON charities (owner_user_id);
ALTER TABLE charities ADD COLUMN IF NOT EXISTS document_data BYTEA;

ALTER TABLE users ADD COLUMN IF NOT EXISTS charity_id BIGINT REFERENCES charities(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS users_charity_id_idx ON users (charity_id);

CREATE TABLE IF NOT EXISTS listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  donor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  campaign_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  condition TEXT NOT NULL CHECK (condition IN ('new', 'like_new', 'good', 'fair')),
  category TEXT NOT NULL,
  images TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  starting_price NUMERIC(12, 2) NOT NULL CHECK (starting_price >= 0),
  current_bid NUMERIC(12, 2) NOT NULL CHECK (current_bid >= 0),
  bid_count INTEGER NOT NULL DEFAULT 0 CHECK (bid_count >= 0),
  status TEXT NOT NULL CHECK (status IN ('draft', 'pending', 'changes_requested', 'charity_review', 'active', 'sold', 'shipped', 'delivered', 'expired', 'cancelled', 'rejected')),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  winner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  charity_name TEXT NOT NULL,
  min_increment NUMERIC(12, 2) NOT NULL CHECK (min_increment > 0),
  -- SFR09: latest reviewer note (admin reject / request-changes reason) shown to the donor.
  review_note TEXT,
  -- SFR09: which stage produced the note — 'admin' (stage 1) or 'charity' (stage 2).
  review_stage TEXT CHECK (review_stage IN ('admin', 'charity')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT listings_time_order_chk CHECK (end_time > start_time)
);

-- FR08 bug fix: reserve price and buy-now price are no longer part of the
-- project workflow. Drop legacy columns when migrating an existing local DB.
ALTER TABLE listings DROP COLUMN IF EXISTS reserve_price;
ALTER TABLE listings DROP COLUMN IF EXISTS buy_now_price;

CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  charity_id BIGINT NOT NULL REFERENCES charities(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  end_date DATE,
  image_data BYTEA,
  image_mime TEXT CHECK (image_mime IS NULL OR image_mime IN ('image/jpeg', 'image/png', 'image/webp')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS campaigns_charity_id_idx ON campaigns (charity_id);
CREATE INDEX IF NOT EXISTS campaigns_status_idx ON campaigns (status);

CREATE INDEX IF NOT EXISTS listings_status_idx ON listings (status);
CREATE INDEX IF NOT EXISTS listings_donor_id_idx ON listings (donor_id);
CREATE INDEX IF NOT EXISTS listings_category_lower_idx ON listings (LOWER(category));

CREATE TABLE IF NOT EXISTS bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bidder_username TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  is_auto_bid BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS bids_listing_amount_idx ON bids (listing_id, amount DESC, created_at ASC);
CREATE INDEX IF NOT EXISTS bids_bidder_listing_idx ON bids (bidder_id, listing_id, created_at DESC);

CREATE TABLE IF NOT EXISTS auto_bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bidder_username TEXT NOT NULL,
  max_amount NUMERIC(12, 2) NOT NULL CHECK (max_amount > 0),
  auto_increment NUMERIC(12, 2) NOT NULL DEFAULT 1 CHECK (auto_increment > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auto_bids_listing_bidder_unique UNIQUE (listing_id, bidder_id)
);

CREATE INDEX IF NOT EXISTS auto_bids_listing_active_max_idx
  ON auto_bids (listing_id, is_active, max_amount DESC, updated_at ASC);
CREATE INDEX IF NOT EXISTS auto_bids_bidder_active_idx
  ON auto_bids (bidder_id, is_active, updated_at DESC);

-- FR12 bug fix: allow each bidder to choose how much their auto-bid increases
-- when it responds. ADD COLUMN keeps existing local databases compatible when
-- npm run migrate is executed after the table already exists.
ALTER TABLE auto_bids
  ADD COLUMN IF NOT EXISTS auto_increment NUMERIC(12, 2) NOT NULL DEFAULT 1 CHECK (auto_increment > 0);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  payment_ref TEXT NOT NULL UNIQUE,
  escrow_state TEXT NOT NULL DEFAULT 'not_held' CHECK (escrow_state IN ('not_held', 'held', 'released')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'successful', 'expired')),
  escrow_release_hash TEXT,
  payment_deadline TIMESTAMPTZ NOT NULL,
  offered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE payments ADD COLUMN IF NOT EXISTS escrow_release_hash TEXT;

CREATE INDEX IF NOT EXISTS payments_listing_status_idx ON payments (listing_id, status, payment_deadline);
CREATE INDEX IF NOT EXISTS payments_bidder_status_idx ON payments (bidder_id, status, payment_deadline);
CREATE UNIQUE INDEX IF NOT EXISTS payments_one_pending_per_listing_uidx ON payments (listing_id) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  tracking_number TEXT,
  courier TEXT,
  shipped_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS deliveries_listing_id_idx ON deliveries (listing_id);

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor_user_id BIGINT,
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  ip_hash TEXT,
  user_agent_hash TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  previous_hash TEXT NOT NULL,
  current_hash TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS audit_events_actor_user_id_idx ON audit_events (actor_user_id);
CREATE INDEX IF NOT EXISTS audit_events_resource_idx ON audit_events (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS audit_events_timestamp_idx ON audit_events (timestamp DESC);

-- Post-sale fulfillment statuses (SFR15) + SFR09 two-stage review statuses.
ALTER TABLE listings ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS review_stage TEXT;
ALTER TABLE listings DROP CONSTRAINT IF EXISTS listings_review_stage_check;
ALTER TABLE listings ADD CONSTRAINT listings_review_stage_check
  CHECK (review_stage IS NULL OR review_stage IN ('admin', 'charity'));
ALTER TABLE listings DROP CONSTRAINT IF EXISTS listings_status_check;
ALTER TABLE listings ADD CONSTRAINT listings_status_check
  CHECK (status IN ('draft', 'pending', 'changes_requested', 'charity_review', 'active', 'sold', 'shipped', 'delivered', 'expired', 'cancelled', 'rejected'));

-- Digital donation receipts — immutable, UNIQUE per payment prevents duplicates
CREATE TABLE IF NOT EXISTS receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_title TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  charity_name TEXT NOT NULL,
  receipt_ref TEXT NOT NULL UNIQUE,
  integrity_hash TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS receipts_bidder_id_idx ON receipts (bidder_id);

-- Payment loop closure: bidder_username identifies the donor on the receipt,
-- payment_ref links back to the payment record for full traceability.
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS bidder_username TEXT NOT NULL DEFAULT '';
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS payment_ref TEXT NOT NULL DEFAULT '';

-- Shipping verification records (SFR15 — donor provides tracking after payment)
CREATE TABLE IF NOT EXISTS shipping_verifications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid            UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id      BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE UNIQUE,
  donor_id        BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
  tracking_number TEXT NOT NULL,
  carrier         TEXT NOT NULL,
  notes           TEXT NOT NULL DEFAULT '',
  shipped_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS shipping_verifications_listing_id_idx ON shipping_verifications (listing_id);

COMMIT;
