BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  full_name TEXT NOT NULL,
  roles TEXT[] NOT NULL DEFAULT ARRAY['bidder']::TEXT[],
  password_hash TEXT NOT NULL,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  contact_number TEXT,
  failed_login_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
  locked_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_roles_valid CHECK (roles <@ ARRAY['bidder', 'donor', 'charity_staff', 'charity', 'admin']::TEXT[])
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx ON users (LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_uidx ON users (LOWER(username));

ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS pending_registrations (
  email TEXT PRIMARY KEY,
  id TEXT NOT NULL,
  username TEXT NOT NULL,
  full_name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  roles TEXT[] NOT NULL,
  otp_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pending_registrations_roles_valid CHECK (roles <@ ARRAY['bidder', 'donor', 'charity_staff', 'charity', 'admin']::TEXT[])
);

CREATE INDEX IF NOT EXISTS pending_registrations_expires_idx ON pending_registrations (expires_at);

CREATE TABLE IF NOT EXISTS sessions (
  sid TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  jti_hash TEXT NOT NULL,
  csrf_token_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  absolute_expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '8 hours',
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Migration: add absolute_expires_at to existing databases
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS absolute_expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '8 hours';

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS password_reset_tokens_expires_idx ON password_reset_tokens (expires_at);

CREATE TABLE IF NOT EXISTS charities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organisation_name TEXT NOT NULL,
  description TEXT NOT NULL,
  document_name TEXT NOT NULL,
  document_mime TEXT NOT NULL CHECK (document_mime IN ('application/pdf', 'image/png', 'image/jpeg')),
  document_sha256 TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS charities_status_idx ON charities (status);
CREATE INDEX IF NOT EXISTS charities_owner_user_id_idx ON charities (owner_user_id);

ALTER TABLE users ADD COLUMN IF NOT EXISTS charity_id BIGINT REFERENCES charities(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS users_charity_id_idx ON users (charity_id);

CREATE TABLE IF NOT EXISTS listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  donor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  campaign_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  condition TEXT NOT NULL CHECK (condition IN ('new', 'like_new', 'good', 'fair')),
  category TEXT NOT NULL,
  images TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  starting_price NUMERIC(12, 2) NOT NULL CHECK (starting_price >= 0),
  reserve_price NUMERIC(12, 2),
  buy_now_price NUMERIC(12, 2),
  current_bid NUMERIC(12, 2) NOT NULL CHECK (current_bid >= 0),
  bid_count INTEGER NOT NULL DEFAULT 0 CHECK (bid_count >= 0),
  status TEXT NOT NULL CHECK (status IN ('draft', 'pending', 'active', 'sold', 'expired', 'cancelled', 'rejected')),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  winner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  charity_name TEXT NOT NULL,
  min_increment NUMERIC(12, 2) NOT NULL CHECK (min_increment > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT listings_time_order_chk CHECK (end_time > start_time)
);

CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  charity_id BIGINT NOT NULL REFERENCES charities(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  end_date DATE,
  image_data BYTEA,
  image_mime TEXT CHECK (image_mime IS NULL OR image_mime IN ('image/jpeg', 'image/png', 'image/webp')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS campaigns_charity_id_idx ON campaigns (charity_id);
CREATE INDEX IF NOT EXISTS campaigns_status_idx ON campaigns (status);

CREATE INDEX IF NOT EXISTS listings_status_idx ON listings (status);
CREATE INDEX IF NOT EXISTS listings_donor_id_idx ON listings (donor_id);
CREATE INDEX IF NOT EXISTS listings_category_lower_idx ON listings (LOWER(category));

CREATE TABLE IF NOT EXISTS bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bidder_username TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  is_auto_bid BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS bids_listing_amount_idx ON bids (listing_id, amount DESC, created_at ASC);
CREATE INDEX IF NOT EXISTS bids_bidder_listing_idx ON bids (bidder_id, listing_id, created_at DESC);

CREATE TABLE IF NOT EXISTS auto_bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bidder_username TEXT NOT NULL,
  max_amount NUMERIC(12, 2) NOT NULL CHECK (max_amount > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auto_bids_listing_bidder_unique UNIQUE (listing_id, bidder_id)
);

CREATE INDEX IF NOT EXISTS auto_bids_listing_active_max_idx
  ON auto_bids (listing_id, is_active, max_amount DESC, updated_at ASC);
CREATE INDEX IF NOT EXISTS auto_bids_bidder_active_idx
  ON auto_bids (bidder_id, is_active, updated_at DESC);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  payment_ref TEXT NOT NULL UNIQUE,
  escrow_state TEXT NOT NULL DEFAULT 'not_held' CHECK (escrow_state IN ('not_held', 'held', 'released', 'refunded')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'successful', 'failed', 'expired')),
  payment_deadline TIMESTAMPTZ NOT NULL,
  offered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS payments_listing_status_idx ON payments (listing_id, status, payment_deadline);
CREATE INDEX IF NOT EXISTS payments_bidder_status_idx ON payments (bidder_id, status, payment_deadline);
CREATE UNIQUE INDEX IF NOT EXISTS payments_one_pending_per_listing_uidx ON payments (listing_id) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor_user_id BIGINT,
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  ip_hash TEXT,
  user_agent_hash TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  previous_hash TEXT NOT NULL,
  current_hash TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS audit_events_actor_user_id_idx ON audit_events (actor_user_id);
CREATE INDEX IF NOT EXISTS audit_events_resource_idx ON audit_events (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS audit_events_timestamp_idx ON audit_events (timestamp DESC);

COMMIT;
