services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # SMTP Port
      - "8025:8025" # Web UI Port
    volumes:
      - ./certs:/certs
      - mailpit-data:/data
    environment:
      - MP_DATABASE=/data/mailpit.db
      
      # --- SMTP TLS Configuration ---
      - MP_SMTP_TLS_CERT=sans:localhost
      - MP_SMTP_TLS_KEY=sans:localhost
      - MP_SMTP_REQUIRE_STARTTLS=false # Forces STARTTLS upgrade
      - MP_SMTP_REQUIRE_TLS=true      # Set true for implicit TLS instead
      - MP_SMTP_AUTH_ACCEPT_ANY=true


volumes:
  mailpit-data:

