import { postgresRepository } from './postgres.repository';

export const repository = postgresRepository;

export const {
  findUserByEmail,
  findUserByUsername,
  findUserById,
  findUserByUuid,
  addUser,
  updateUser,
  toPublicUser,
  listStaffByCharityId,
  savePendingRegistration,
  getPendingRegistration,
  removePendingRegistration,
  saveLoginOtp,
  getLoginOtp,
  removeLoginOtp,
  addSession,
  getSession,
  updateSession,
  revokeSession,
  revokeAllSessionsByUserId,
  savePasswordResetToken,
  getPasswordResetTokenByEmail,
  removePasswordResetToken,
  addCharity,
  getCharityById,
  getCharityByUuid,
  getCharityByOwnerUserId,
  listCharities,
  updateCharity,
  addCampaign,
  getCampaignById,
  getCampaignByUuid,
  getCampaignImage,
  listCampaignsByCharity,
  listAllActiveCampaigns,
  updateCampaign,
  closeCampaign,
  addListing,
  getListingById,
  getListingByUuid,
  updateListing,
  listListings,
  listActiveListings,
  listPendingListings,
  listListingsByDonor,
  listUsers,
  addBid,
  getBidsForListing,
  getBidsByBidder,
  upsertAutoBid,
  getAutoBidForBidder,
  listActiveAutoBidsForListing,
  listAutoBidsByBidder,
  deactivateAutoBid,
  withListingLock,
  addPayment,
  updatePayment,
  getPaymentByUuid,
  getPaymentsForListing,
  getPendingPaymentForListing,
  listPaymentsByBidder,
  withPaymentLock,
  appendAuditEvent,
  listAuditEvents,
  userRolesInclude,
} = repository;

export type {
  BidForGoodRepository,
  NewAuditEventInput,
  NewAutoBidInput,
  NewBidInput,
  NewCharityInput,
  NewListingInput,
  NewPaymentInput,
  NewUserInput,
  PublicUser,
} from './repository.types';
