import { postgresRepository } from './postgres.repository';

export const repository = postgresRepository;

export const {
  findUserByEmail,
  findUserByUsername,
  findUserById,
  findUserByUuid,
  addUser,
  updateUser,
  toPublicUser,
  listStaffByCharityId,
  savePendingRegistration,
  getPendingRegistration,
  removePendingRegistration,
  addSession,
  getSession,
  updateSession,
  revokeSession,
  addCharity,
  getCharityById,
  getCharityByUuid,
  getCharityByOwnerUserId,
  listCharities,
  updateCharity,
  addCampaign,
  getCampaignByUuid,
  getCampaignImage,
  listCampaignsByCharity,
  updateCampaign,
  closeCampaign,
  addListing,
  getListingById,
  getListingByUuid,
  updateListing,
  listListings,
  listActiveListings,
  listPendingListings,
  addBid,
  getBidsForListing,
  withListingLock,
  appendAuditEvent,
  listAuditEvents,
  userRolesInclude,
} = repository;

export type {
  BidForGoodRepository,
  NewAuditEventInput,
  NewBidInput,
  NewCharityInput,
  NewListingInput,
  NewUserInput,
  PublicUser,
} from './repository.types';
